FROM maven:3.8.4-openjdk-11-slim AS builder

WORKDIR /app

COPY pom.xml .
RUN mvn dependency:go-offline

COPY src ./src
RUN mvn package -DskipTests

FROM openjdk:11-jre-slim

WORKDIR /app

COPY --from=builder /app/target/kafka-producer-1.0-SNAPSHOT.jar .

CMD ["java", "-jar", "kafka-producer-1.0-SNAPSHOT.jar"]
